### ISSUE TITLE
Подготовить описание проекта для Microsoft

### ISSUE THREAD

**Issue by RSamokhin** [TeamPlate/OnMiner#1]
для регистрации на Bizspark 2500 символов 
на английском языке
- [x] первичный текст
- [ ] проверка и вычитка
- [ ] обновление README

**Comment by RSamokhin** [comment]
Поправь пожалуйста форматирование  того, что в ридми вынес
И фидбек от нейтива pls

**Comment by RSamokhin** [comment]
Леш, нейтив спикер не проверил?

**Comment by jgc128** [comment]
Нет еще пока, видимо( Мы с ним на этапе обсуждения цены застряли((

**Comment by RSamokhin** [comment]
цены??? Алексей:)давай его в лес

**Comment by jgc128** [comment]
Ну он по любому будет проверять мои следующие тексты, чисто для практики английского, так что не волнуйся)

**Comment by RSamokhin** [comment]
Антон, проверь пожалуйста, Readme проекта

**Comment by RSamokhin** [comment]
принимаем описание как есть :)
