### ISSUE TITLE
Развернуть виртуальную машину и настроить резервное копирование

### ISSUE THREAD

**Issue by RSamokhin** [TeamPlate/OnMiner#9]
на азуре

**Comment by RSamokhin** [comment]
Виртуальная машина onmine.cloudapp.net создана 2 ядра, 4 ГБ Рам
Резервное копирование будет осуществляться с помощью создания образов

**Comment by jgc128** [comment]
Она на линуксе? Под него нет Azure Backup?

**Comment by RSamokhin** [comment]
Она на Debiane, нету, вроде. Проблема с резервирован тем машины а не бэкапа файлов, я не нашел иные способы, кроме создания образов системы
